name: KernelMethods
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - openssl=1.1.1i
  - pip=20.3.3
  - python=3.7.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - zlib=1.2.11
