name: KernelMethods
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - icc_rt=2019.0.0
  - intel-openmp=2020.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1i
  - pandas=1.2.1
  - pip=20.3.3
  - python=3.7.1
  - python-dateutil=2.8.1
  - pytz=2021.1
  - scipy=1.6.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - zlib=1.2.11
